Integrate the DpathEnhancingExtractor in the UI of Airbyte. Created a DPath Enhancing Extractor Refactored the record enhancement logic - moved to the extracted class Split the tests of DPathExtractor and DPathEnhancingExtractor
Fix the failing tests:

FAILED unit_tests/sources/declarative/parsers/test_model_to_component_factory.py::test_create_custom_components[test_create_custom_component_with_subcomponent_that_uses_parameters]
FAILED unit_tests/sources/declarative/parsers/test_model_to_component_factory.py::test_custom_components_do_not_contain_extra_fields
FAILED unit_tests/sources/declarative/parsers/test_model_to_component_factory.py::test_parse_custom_component_fields_if_subcomponent
FAILED unit_tests/sources/declarative/parsers/test_model_to_component_factory.py::test_create_page_increment
FAILED unit_tests/sources/declarative/parsers/test_model_to_component_factory.py::test_create_offset_increment
FAILED unit_tests/sources/file_based/test_file_based_scenarios.py::test_file_based_read[simple_unstructured_scenario]
FAILED unit_tests/sources/file_based/test_file_based_scenarios.py::test_file_based_read[no_file_extension_unstructured_scenario]

They faile because of comparing string and int values of the page_size (public) attribute.
Imposed an invariant:
  on construction, page_size can be set to a string or int
  keep only values of one type in page_size for uniform comparison (convert the values of the other type)
  _page_size holds the internal / working value
... unless manipulated directly.

Merged:
feat(low-code concurrent): Allow async job low-code streams that are incremental to be run by the concurrent framework (#228)
fix(low-code): Fix declarative low-code state migration in SubstreamPartitionRouter (#267)
feat: combine slash command jobs into single job steps (#266)
feat(low-code): add items and property mappings to dynamic schemas (#256)
feat: add help response for unrecognized slash commands (#264)
ci: post direct links to html connector test reports (#252) (#263)
fix(low-code): Fix legacy state migration in SubstreamPartitionRouter (#261)
fix(airbyte-cdk): Fix RequestOptionsProvider for PerPartitionWithGlobalCursor (#254)
feat(low-code): add profile assertion flow to oauth authenticator component (#236)
feat(Low-Code Concurrent CDK): Add ConcurrentPerPartitionCursor (#111)
fix: don't mypy unit_tests (#241)
fix: handle backoff_strategies in CompositeErrorHandler (#225)
feat(concurrent cursor): attempt at clamping datetime (#234)
fix(airbyte-cdk): Fix RequestOptionsProvider for PerPartitionWithGlobalCursor (#254)
feat(low-code): add profile assertion flow to oauth authenticator component (#236)
feat(Low-Code Concurrent CDK): Add ConcurrentPerPartitionCursor (#111)
fix: don't mypy unit_tests (#241)
fix: handle backoff_strategies in CompositeErrorHandler (#225)
feat(concurrent cursor): attempt at clamping datetime (#234)
ci: use `ubuntu-24.04` explicitly (resolves CI warnings) (#244)
Fix(sdm): module ref issue in python components import (#243)
feat(source-declarative-manifest): add support for custom Python components from dynamic text input (#174)
chore(deps): bump avro from 1.11.3 to 1.12.0 (#133)
docs: comments on what the `Dockerfile` is for (#240)
chore: move ruff configuration to dedicated ruff.toml file (#237)
Fix(sdm): module ref issue in python components import (#243)
feat(low-code): add DpathFlattenFields (#227)
feat(source-declarative-manifest): add support for custom Python components from dynamic text input (#174)
chore(deps): bump avro from 1.11.3 to 1.12.0 (#133)
docs: comments on what the `Dockerfile` is for (#240)
chore: move ruff configuration to dedicated ruff.toml file (#237)