Implement https://github.com/airbytehq/airbyte/issues/50395 discussed in https://github.com/airbytehq/airbyte/discussions/49971
At record extraction step, in each record add the service field $root holding a reference to:
* the root response object, when parsing JSON format
* the original record, when parsing JSONL format
that each record to process is extracted from.
More service fields could be added in future.
The service fields are available in the record's filtering and transform steps.

Avoid:
* reusing the maps/dictionaries produced, thus avoid building cyclic structures
* transforming the service fields in the Flatten transformation.

Explicitly cleanup the service field(s) after the transform step, thus making them:
* local for the filter and transform steps
* not visible to the next mapping and store steps (as they should be)
* not visible in the tests beyond the test_record_selector (as they should be)
This allows the record transformation logic to define its "local variables" to reuse
some interim calculations.

The contract of body parsing seems irregular in representing the cases of bad JSON, no JSON and empty JSON.
Cannot be unified as that that irregularity is already used.

Update the development environment setup documentation
* to organize and present the setup steps explicitly
* to avoid misunderstandings and wasted efforts.

Update CONTRIBUTING.md to
* collect and organize the knowledge on running the test locally.
* state the actual testing steps.
* clarify and make explicit the procedures and steps.

The unit, integration, and acceptance tests in this exactly version succeed under Fedora 41, while
one of them fails under Oracle Linux 8.7. not related to the contents of this PR.
The integration tests of the CDK fail due to missing `secrets/config.json` file for the Shopify source.
See https://github.com/airbytehq/airbyte-python-cdk/issues/197

Polish

Integrate the DpathEnhancingExtractor in the UI of Airbyte.
Created a DPath Enhancing Extractor
Refactored the record enhancement logic - moved to the extracted class
Split the tests of DPathExtractor and DPathEnhancingExtractor

Fix the failing tests:

FAILED unit_tests/sources/declarative/parsers/test_model_to_component_factory.py::test_create_custom_components[test_create_custom_component_with_subcomponent_that_uses_parameters]
FAILED unit_tests/sources/declarative/parsers/test_model_to_component_factory.py::test_custom_components_do_not_contain_extra_fields
FAILED unit_tests/sources/declarative/parsers/test_model_to_component_factory.py::test_parse_custom_component_fields_if_subcomponent
FAILED unit_tests/sources/declarative/parsers/test_model_to_component_factory.py::test_create_page_increment
FAILED unit_tests/sources/declarative/parsers/test_model_to_component_factory.py::test_create_offset_increment
FAILED unit_tests/sources/file_based/test_file_based_scenarios.py::test_file_based_read[simple_unstructured_scenario]
FAILED unit_tests/sources/file_based/test_file_based_scenarios.py::test_file_based_read[no_file_extension_unstructured_scenario]

They faile because of comparing string and int values of the page_size (public) attribute.
Imposed an invariant:
  on construction, page_size can be set to a string or int
  keep only values of one type in page_size for uniform comparison (convert the values of the other type)
  _page_size holds the internal / working value
... unless manipulated directly.

Merged:
feat(low-code concurrent): Allow async job low-code streams that are incremental to be run by the concurrent framework (#228)
fix(low-code): Fix declarative low-code state migration in SubstreamPartitionRouter (#267)
feat: combine slash command jobs into single job steps (#266)
feat(low-code): add items and property mappings to dynamic schemas (#256)
feat: add help response for unrecognized slash commands (#264)
ci: post direct links to html connector test reports (#252) (#263)
fix(low-code): Fix legacy state migration in SubstreamPartitionRouter (#261)
fix(airbyte-cdk): Fix RequestOptionsProvider for PerPartitionWithGlobalCursor (#254)
feat(low-code): add profile assertion flow to oauth authenticator component (#236)
feat(Low-Code Concurrent CDK): Add ConcurrentPerPartitionCursor (#111)
fix: don't mypy unit_tests (#241)
fix: handle backoff_strategies in CompositeErrorHandler (#225)
feat(concurrent cursor): attempt at clamping datetime (#234)
fix(airbyte-cdk): Fix RequestOptionsProvider for PerPartitionWithGlobalCursor (#254)
feat(low-code): add profile assertion flow to oauth authenticator component (#236)
feat(Low-Code Concurrent CDK): Add ConcurrentPerPartitionCursor (#111)
fix: don't mypy unit_tests (#241)
fix: handle backoff_strategies in CompositeErrorHandler (#225)
feat(concurrent cursor): attempt at clamping datetime (#234)
ci: use `ubuntu-24.04` explicitly (resolves CI warnings) (#244)
Fix(sdm): module ref issue in python components import (#243)
feat(source-declarative-manifest): add support for custom Python components from dynamic text input (#174)
chore(deps): bump avro from 1.11.3 to 1.12.0 (#133)
docs: comments on what the `Dockerfile` is for (#240)
chore: move ruff configuration to dedicated ruff.toml file (#237)
Fix(sdm): module ref issue in python components import (#243)
feat(low-code): add DpathFlattenFields (#227)
feat(source-declarative-manifest): add support for custom Python components from dynamic text input (#174)
chore(deps): bump avro from 1.11.3 to 1.12.0 (#133)
docs: comments on what the `Dockerfile` is for (#240)
chore: move ruff configuration to dedicated ruff.toml file (#237)

formatted

Update record_extractor.py

Trigger a new build. Hopefully, the integration test infrastructure is fixed.

Update CONTRIBUTING.md

Trigger a new build